name: terra_dart_keys
description: A lightweight key management library for the terra ecosystem
version: 1.1.4
homepage: "https://github.com/TerraMystics"
repository: "https://github.com/TerraMystics/Terra.Dart.Extensions"
documentation: "https://docs.terra.money/"
funding:
  - "https://www.buymeacoffee.com/dangenius"
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  protobuf_google: ^0.0.1
  terra_dart_sdk_extensions: ^1.0.5
  dart_bech32: ^2.0.0
  common_utils: ^2.1.0
  coinslib: ^3.1.7
  bip39: ^1.0.6
  bip32: ^2.0.0
  crypto: ^3.0.2
  buffer: ^1.2.0
  ecdsa: ^0.0.4
  elliptic: ^0.3.8
  hex: ^0.2.0
  sec: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
