name: terra_dart_keys
description: A lightweight key management library for the terra ecosystem
version: 1.0.1
homepage: "https://github.com/TerraMystics"
repository: "https://github.com/TerraMystics/Terra.Dart.Extensions"
documentation: "https://docs.terra.money/"
funding:
  - "https://www.buymeacoffee.com/dangenius"
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  protobuf_google: ^0.0.1
  terra_dart_sdk_extensions: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
